# Tarefa 01

- Leia os enunciados com atenção
- Saiba que pode haver mais de uma resposta correta
- Insira novas células de código sempre que achar necessário
- Em caso de dúvidas, procure os monitores
- Divirta-se :)

In [11]:
from pandas_datareader import data as pdr

import plotly.express as px
from plotly import graph_objects
import yfinance as yf
yf.pdr_override()

import datetime as dt
import pandas as pd
import numpy as np

#### 1. Baixando dados de ativos
    1. Baixe os dados de três ativos da sua escolha do Yahoo Finance, correspondente a um período de pelo menos 2 anos até a data mais recente.
    2. Salve esses dados para que você possa utilizá-los na próxima tarefa.

In [17]:
%%time

start_date = dt.datetime(2021, 1, 1)
end_date = dt.datetime(2021, 12, 31)

df = pdr.get_data_yahoo(['AMZN', '0992.HK', 'AAPL'], start=start_date, end=end_date)
df.head()

[*********************100%***********************]  3 of 3 completed
Wall time: 342 ms

           Adj Close                           Close                          \
             0992.HK        AAPL        AMZN 0992.HK        AAPL        AMZN
Date
2021-01-04  6.937774  127.679993  159.331497    7.62  129.410004  159.331497
2021-01-05  6.946879  129.258606  160.925507    7.63  131.009995  160.925507
2021-01-06  6.810309  124.907562  156.919006    7.48  126.599998  156.919006
2021-01-07  6.883146  129.169800  158.108002    7.56  130.919998  158.108002
2021-01-08  7.201811  130.284698  159.134995    7.91  132.050003  159.134995

              High                             Low                          \
           0992.HK        AAPL        AMZN 0992.HK        AAPL        AMZN
Date
2021-01-04    7.68  133.610001  163.600006    7.18  126.760002  157.201004
2021-01-05    7.68  131.740005  161.169006    7.33  128.429993  158.253006
2021-01-06    7.67  131.050003  159.875504    7.42  126.379997  156.557999
2021-01-07    7.73  131.630005  160.427002    7.30  127.860001  157.750000
2021-01-08    7.95  132.630005  159.531998    7.52  130.229996  157.110001

              Open                              Volume               \
           0992.HK        AAPL        AMZN     0992.HK         AAPL
Date
2021-01-04    7.18  133.520004  163.500000  83611650.0  143301900.0
2021-01-05    7.48  128.889999  158.300507  54929799.0   97664900.0
2021-01-06    7.50  127.720001  157.324005  74271331.0  155088000.0
2021-01-07    7.46  128.360001  157.850006  84604245.0  109578200.0
2021-01-08    7.56  132.429993  159.000000  86075192.0  105158200.0


                  AMZN
Date
2021-01-04  88228000.0
2021-01-05  53110000.0
2021-01-06  87896000.0
2021-01-07  70290000.0
2021-01-08  70754000.0

#### 2. Observando a volatilidade dentro do dia
1. Calcule a amplitude de variação do valor do ativo dentro do dia. Essa amplitude você pode calcular com um comando simples de adicionar uma coluna no Pandas: (valor máximo - valor mínimo).
2. Monte um gráfico de linha mostrando a variação dessa amplitude ao longo do período coletado, por ativo.
3. Veja se consegue identificar que ativo apresentou maior volatilidade.